# Generated by Django 3.2.8 on 2021-10-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('registered_country', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNumber', models.IntegerField()),
                ('length', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('cell_area', models.IntegerField()),
                ('cell_technology', models.CharField(max_length=20)),
                ('total_number_of_cells', models.IntegerField()),
                ('total_number_of_cells_in_series', models.IntegerField()),
                ('number_of_series_strings', models.IntegerField()),
                ('nuber_of_bypass_diodes', models.IntegerField()),
                ('series_fuse_rating', models.CharField(max_length=20)),
                ('interconnect_material', models.CharField(max_length=20)),
                ('interconnect_supplier', models.CharField(max_length=20)),
                ('superstrate_type', models.CharField(max_length=20)),
                ('substrate_type', models.CharField(max_length=20)),
                ('substrate_manufacturer', models.CharField(max_length=20)),
                ('frame_material', models.CharField(max_length=20)),
                ('frame_adhesive', models.CharField(max_length=20)),
                ('encapsulant_type', models.CharField(max_length=20)),
                ('encapsulant_manufacturer', models.CharField(max_length=20)),
                ('junction_box_type', models.CharField(max_length=20)),
                ('junction_box_manufacturer', models.CharField(max_length=20)),
                ('junction_box_material', models.CharField(max_length=20)),
                ('cable_type', models.CharField(max_length=20)),
                ('connector_type', models.CharField(max_length=20)),
                ('maximum_system_voltage', models.IntegerField()),
                ('rated_voc', models.CharField(max_length=20)),
                ('rated_isc', models.CharField(max_length=20)),
                ('rated_vmp', models.CharField(max_length=20)),
                ('rated_imp', models.CharField(max_length=20)),
                ('rated_pmp', models.CharField(max_length=20)),
                ('rated_ff', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.CharField(max_length=20)),
                ('reportingCondition', models.CharField(max_length=20)),
                ('testSequence', models.CharField(max_length=20)),
                ('testDate', models.CharField(max_length=20)),
                ('isc', models.CharField(max_length=20)),
                ('voc', models.CharField(max_length=20)),
                ('imp', models.CharField(max_length=20)),
                ('vpm', models.CharField(max_length=20)),
                ('pmp', models.CharField(max_length=20)),
                ('ff', models.CharField(max_length=20)),
                ('noct', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('officePhone', models.IntegerField()),
                ('cellPhone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
